Ref #230 : Added a new Tag page and the tag generation logic.
LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura pull request #231
Opened 2020-09-10 22:20 UTC by Yann-BUTSCHER-EIRL

Added :
- New tag controller
- New tag service
- New tag index template
- New tag PDF template

Modified :
- Base template : Added a link to the tag index page in the navbar

2020-09-10 22:30 UTC, LucileDT requested changes

2020-09-10 22:30 UTC, LucileDT commented on src/Controller/TagController.php
> +<?php
Please add comments to this controller to explain what it does

2020-09-10 22:30 UTC, LucileDT commented on public/css/PDF/tag.css
> +.tag-row {
No need for a class, you can use the `tr` selector

2020-09-10 22:30 UTC, LucileDT commented on src/Service/TagService.php
> +     * Generate a single pdf file containing all the tags corresponding to a list of given people addresses.
Could you add how many tags a page contains?

2020-09-10 22:30 UTC, LucileDT commented on templates/PDF/Tag/_tag.html.twig
> +</html>
Missing new line at end of file

2020-09-10 22:30 UTC, LucileDT commented on templates/Tag/index.html.twig
> +{% endblock %}
Missing new line at end of file

2020-10-05 11:11 UTC, LucileDT commented
@Yann-BUTSCHER-EIRL I need you to fix things related to my comments to merge your pull request.

2020-12-13 18:29 UTC, LucileDT approved these changes

2020-12-13 19:10 UTC, Yann-BUTSCHER-EIRL commented
@LucileDT I added all the changes you requested.
Can you validate again and merge if all is good, please?

2020-12-14 16:09 UTC, LucileDT commented
All good thanks!

2020-12-14 16:09 UTC, merged